[tool.poetry]
name = "-"
version = "0.1.0"
description = ""
authors = ["Kevin <kevinhernem@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^2.6.1"
box2d = "^2.3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
